main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('', include('clothes.urls')),
    path('', include('employees.urls')),
    path('', include('parser_app.urls')),
    path('', include('tv_show.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

tv_show/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('movies/', views.MovieList.as_view(), name='movie_list'),
    path('movies/<int:id>/', views.MovieDetail.as_view()),
    path('movies/<int:id>/edit/', views.MovieEdit.as_view()),
    path('movies/add/', views.AddMovie.as_view(), name='add_movie'),
    path('movies/<int:id>/drop/', views.MovieDrop.as_view()),
    path('review/', views.Review.as_view()),

    path('movies/thriller/', views.ThrillerFilter.as_view()),
    path('movies/comedy/', views.ComedyFilter.as_view()),
    path('movies/fantasy/', views.FantasyFilter.as_view()),
]

templates/movies/add_movie.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add movies</title>
</head>
<body>

<form action="/movies/add/" method="POST" enctype="multipart/form-data">
    <h3>Добавить фильм</h3>
    {% csrf_token %}
    {{ form.as_p }}
<input type="submit" value="Завершить">
</form>

</body>
</html>

templates/movies/comedy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Comedy</title>
</head>
<body>

<h1>Comedy films</h1>
{% for i in comedy %}
    <h3>{{ i.title }}</h3>
    <img src="{{ i.image.url }}" alt="">
{% endfor %}

</body>
</html>

templates/movies/fantasy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Fantasy</title>
</head>
<body>

<h1>Fantasy films</h1>
{% for i in fantasy %}
    <h3>{{ i.title }}</h3>
    <img src="{{ i.image.url }}" alt="">
{% endfor %}

</body>
</html>

templates/movies/movie_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ movie_id.title }}</title>
</head>
<body>

<h1>{{ movie_id.title }}</h1>
<img src="{{ movie_id.image.url }}" alt="" width="300" height="400">
<p>{{ movie_id.description }}</p>
<p>{{ movie_id.genre }}</p>
<p>{{ movie_id.price }} {{ movie_id.created_at }}</p>
<br>

{% for j in movie_id.movie.all %}
    <center>
    <h3>{{ j.user }}</h3>
    <h4>{{ j.comment }}</h4>
    <p>{{ j.rating }} stars</p>
    <p>{{ j.created_at }}</p>
    </center>
{% endfor %}

<a href="/review/">Добавить комментарий</a>

</body>
</html>

templates/movies/movie_drop.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete movies</title>
</head>
<body>

<form method="POST" enctype="multipart/form-data">
    <h1>Вы точно хотите удалить этот фильм?</h1>
    {% csrf_token %}
    <button type="submit">ДА</button>
    <button><a href="{% url 'movies:movie_list' %}">Назад</a></button>
</form>

</body>
</html>

templates/movies/movie_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit movies</title>
</head>
<body>

<form method="POST" enctype="multipart/form-data">
    <h3>Редактировать</h3>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить изменения">
</form>

</body>
</html>

templates/movies/movie_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movies</title>
</head>
<body>
<p><a href="/movies/comedy/">Фильмы жанра комедия</a></p>
<p><a href="/movies/thriller/">Фильмы жанра триллер,ужасы</a></p>
<p><a href="/movies/fantasy/">Фильмы жанра фантастика</a></p>
<br><br>
<a href="{% url 'movies:add_movie' %}">Добавить</a>
<br><br><br>
{% for i in movie_list %}
    <h1>{{ i.title }}</h1>
    <img src="{{ i.image.url }}" alt="" width="300" height="400">
    <h2>{{ i.genre }}</h2>
    <button><a href="/movies/{{ i.id }}/">Подробнее</a></button>
    <br>
    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <button><a href="/movies/{{ i.id }}/drop/">Удалить</a></button>
    <button><a href="/movies/{{ i.id }}/edit/">Редактировать</a></button>
    </form>
{% endfor %}

</body>
</html>

templates/movies/review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Комментарий</title>
</head>
<body>

<form action="/review/" method="POST" enctype="multipart/form-data">
    <h3>Добавить комментарий</h3>
    {% csrf_token %}
    {{ form.as_p }}
<input type="submit" value="Отправить">
</form>


</body>
</html>

templates/movies/thriller.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Thriller</title>
</head>
<body>

<h1>Thriller films</h1>
{% for i in thriller %}
    <h3>{{ i.title }}</h3>
    <img src="{{ i.image.url }}" alt="">
{% endfor %}

</body>
</html>