books/urls.py
from django.urls import path
from . import views

app_name = 'books'
urlpatterns = [
    path('', views.BookListView.as_view(), name='book_list'),
    path('book_list/<int:id>/', views.BookDetailView.as_view()),

    path('add_book/', views.AddBookView.as_view(), name='add_book'),
    path('book_list_delete/', views.BookListDeleteView.as_view(), name='book_list_delete'),
    path('book_list/<int:id>/delete/', views.BookDropView.as_view()),
    path('book_list_edit/', views.BookListEditView.as_view(), name='book_list_edit'),
    path('book_list/<int:id>/edit/', views.UpdateBookView.as_view()),

    path('search/', views.SearchView.as_view(), name='search'),

    path('myinfo/', views.myinfo_view),
    path('friend/', views.friend_view),
    path('time/', views.time_view),
]

clothes/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('clothes/', views.ClothesFilterView.as_view()),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('', include('clothes.urls')),
    path('', include('employees.urls')),
    path('', include('parser_app.urls')),
    path('', include('tv_show.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

clothes/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=100, db_index=True, null=True)

    def __str__(self):
        return self.name


class Cloth(models.Model):
    name = models.CharField(max_length=250, db_index=True, null=True)
    price = models.FloatField(db_index=True, null=True)
    description = models.TextField(db_index=True, null=True)
    tags = models.ManyToManyField(Tag, db_index=True)

    def __str__(self):
        return self.name

clothes/views.py
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.decorators.cache import cache_page
from . import models


@method_decorator(cache_page(60*15), name='dispatch')
class ClothesFilterView(generic.ListView):
    template_name = 'clothes.html'
    context_object_name = 'kids_cloth' 'adults_cloth' 'pensioners_cloth'
    model = models.Cloth

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['kids'] = models.Cloth.objects.filter(tags__name='для детей').order_by('-id')
        context['adults'] = models.Cloth.objects.filter(tags__name='для взрослых').order_by('-id')
        context['pensioners'] = models.Cloth.objects.filter(tags__name='для пенсионеров').order_by('-id')
        return context

# def clothes_filter_view(request):
#     if request.method == 'GET':
#         kids_cloth = models.Cloth.objects.filter(tags__name='для детей').order_by('-id')
#         adults_cloth = models.Cloth.objects.filter(tags__name='для взрослых').order_by('-id')
#         pensioners_cloth = models.Cloth.objects.filter(tags__name='для пенсионеров').order_by('-id')
#         return render(
#             request,
#             template_name='clothes.html',
#             context={
#                 'kids_cloth': kids_cloth,
#                 'adults_cloth': adults_cloth,
#                 'pensioners_cloth': pensioners_cloth
#             }
#         )

templates/book_detail.html
{% include 'header.html' %}

<h1>{{ book_id.title }} {{ book_id.author }}</h1>
<img src="{{ book_id.cover.url }}" alt="">
<p>{{ book_id.genre }} {{ book_id.price }} сом {{ book_id.pages }} страниц</p>
<p>{{ book_id.desciption }}</p>
<p>Произведение было написано {{ book_id.created_at }}</p>
<a href="{{ book_id.publisher_url }}">Перейти на сайт</a>
<p>{{ book_id.publisher_email }}</p>

{% for j in book_id.book_review.all %}
    <h3>{{ j.review_text }}</h3>
    <p>{{ j.created_at }}</p>
{% endfor %}

{% include 'footer.html' %}

templates/book_list.html
{% load static %}
{% include 'header.html' %}
<link rel="stylesheet" href="{% static 'css/book_list.css' %}">

<h1>Все книги</h1>

<div class="square_mom">
{% for i in book_object %}
    <div class="card" style="width: 18rem;">
        <img src="{{ i.cover.url }}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">{{ i.title }} {{ i.author }}</h5>
            <p class="card-text">{{ i.price }} сом {{ i.genre }}</p>
            <a href="/book_list/{{ i.id }}/" class="btn btn-primary">Подробнее</a>
        </div>
    </div>
{% endfor %}
</div>

{% include 'footer.html' %}

templates/clothes.html
{% include 'header.html' %}
<br><br><br>
<h1>Одежда для детей</h1>
{% for i in kids_cloth %}
<h2>
    {{  i.name }}
</h2>
{% endfor %}
<br>

<h1>Одежда для взрослых</h1>
{% for i in adults_cloth %}
<h2>
    {{  i.name }}
</h2>
{% endfor %}
<br>

<h1>Одежда для пенсионеров</h1>
{% for i in pensioners_cloth %}
<h2>
    {{  i.name }}
</h2>
{% endfor %}



{% include 'footer.html' %}

templates/footer.html
<footer class="bg-body-tertiary text-center text-lg-start">
  <!-- Grid container -->
  <div class="container p-4">
    <!--Grid row-->
    <div class="row">
      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <h5 class="text-uppercase">Главная</h5>

        <ul class="list-unstyled mb-0">
          <li>
            <a href="#!" class="text-body">Link 1</a>
          </li>
          <li>
            <a href="#!" class="text-body">Link 2</a>
          </li>
          <li>
            <a href="#!" class="text-body">Link 3</a>
          </li>
          <li>
            <a href="#!" class="text-body">Link 4</a>
          </li>
        </ul>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <h5 class="text-uppercase mb-0">Контакты</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!" class="text-body">Link 1</a>
          </li>
          <li>
            <a href="#!" class="text-body">Link 2</a>
          </li>
          <li>
            <a href="#!" class="text-body">Link 3</a>
          </li>
          <li>
            <a href="#!" class="text-body">Link 4</a>
          </li>
        </ul>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <h5 class="text-uppercase">Наши соцсети</h5>

        <ul class="list-unstyled mb-0">
          <li>
            <a href="#!" class="text-body">Link 1</a>
          </li>
          <li>
            <a href="#!" class="text-body">Link 2</a>
          </li>
          <li>
            <a href="#!" class="text-body">Link 3</a>
          </li>
          <li>
            <a href="#!" class="text-body">Link 4</a>
          </li>
        </ul>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <h5 class="text-uppercase mb-0">Адрес</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!" class="text-body">Link 1</a>
          </li>
          <li>
            <a href="#!" class="text-body">Link 2</a>
          </li>
          <li>
            <a href="#!" class="text-body">Link 3</a>
          </li>
          <li>
            <a href="#!" class="text-body">Link 4</a>
          </li>
        </ul>
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2024 Copyright
  </div>
  <!-- Copyright -->
</footer>

</body>
</html>

templates/header.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Book-store</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar  bg-dark border-bottom border-body navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'books:book_list' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Ассортимент книг
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'books:add_book' %}">Добавить</a></li>
            <li><a class="dropdown-item" href="{% url 'books:book_list_delete' %}">Удалить</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'books:book_list_edit' %}">Редактировать</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form action="{% url 'books:search' %}" method="GET" class="d-flex" role="search">
        <input class="form-control me-2" name="q" type="text" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>